### ISSUE TITLE
Issues with binfmts

### ISSUE THREAD

**Issue by daniviga** [gem/oq-python-deb#3]
We are either put the `binfmts` in the wrong folder and trying to use it here:

https://github.com/gem/oq-python-deb/blob/9466f5450527d405ede81a5cc2b40446ca6eccc1/PVER-minimal.postinst.in#L27

This gives an error during the installation phase on a machine with support for `binfmts`.

I'm proposing to just disable the `update-binfmts` hook, since having our python registered in the system can conflict with upstream.

Reported here: https://groups.google.com/forum/#!topic/openquake-users/_icRIXAEmZE

**Comment by nastasi-oq** [comment]
Fix with 3e3599b39f379ca79e03208d415b4d01c4634235

**Comment by nastasi-oq** [comment]
Wrong comment to close it, closed manually.
